<?php $helper = Mage::helper('adminhtml'); ?>
<h1>Manage Product Tree</h1>

<div id="treePanelContainer"></div>

<?php echo $this->getChildHtml('grid'); ?>

<div id="productTreeNodeManagerMetadata" style="display: none;"
     data-readUrl="<?php echo $helper->getUrl('adminhtml/admin_manage_ProductTrees/fetchProductTrees'); ?>"
     data-addUrl="<?php echo $helper->getUrl('adminhtml/admin_manage_ProductTrees/addToProductTree') ?>"
    > </div>