<div id="aggregateTableContainer">
    <table id="aggregateTable" class="trsChart">
        <thead>
        <th>Number of Orders</th>
        <th>Total Items Sold</th>
        <th>Total Revenue</th>
        </thead>
        <tr>
            <td id="ordersCell">

            </td>
            <td id="soldCell">

            </td>
            <td id="revenueCell">

            </td>
        </tr>
    </table>
</div>